spring:
  application:
    name: Java-Code-Sandbox
server:
  port: 8100
docker:
  imageName: openjdk:8-jre-alpine
  firstInitImage: false
  PreContainers: 10 # 预创建容器数
knife4j:
  enable: true
  openapi:
    title: Knife4j接口文档
    description: 代码沙箱调用接口
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - insane.controller